export default [
    'align-Content',
    'align-Items',
    'align-Self',
    'alignment-Baseline',
    'all',
    'animation',
    'animation-Delay',
    'animation-Direction',
    'animation-Duration',
    'animation-Fill-Mode',
    'animation-Iteration-Count',
    'animation-Name',
    'animation-Play-State',
    'animation-Timing-Function',
    'backface-Visibility',
    'background',
    'background-Attachment',
    'background-Clip',
    'background-Color',
    'background-Image',
    'background-Origin',
    'background-Position',
    'background-Position-X',
    'background-Position-Y',
    'background-Repeat',
    'background-Size',
    'baseline-Shift',
    'block-Size',
    'border',
    'border-Block-End',
    'border-Block-End-Color',
    'border-Block-End-Style',
    'border-Block-End-Width',
    'border-Block-Start',
    'border-Block-Start-Color',
    'border-Block-Start-Style',
    'border-Block-Start-Width',
    'border-Bottom',
    'border-Bottom-Color',
    'border-Bottom-Left-Radius',
    'border-Bottom-Right-Radius',
    'border-Bottom-Style',
    'border-Bottom-Width',
    'border-Collapse',
    'border-Color',
    'border-Image',
    'border-Image-Outset',
    'border-Image-Repeat',
    'border-Image-Slice',
    'border-Image-Source',
    'border-Image-Width',
    'border-Inline-End',
    'border-Inline-End-Color',
    'border-Inline-End-Style',
    'border-Inline-End-Width',
    'border-Inline-Start',
    'border-Inline-Start-Color',
    'border-Inline-Start-Style',
    'border-Inline-Start-Width',
    'border-Left',
    'border-Left-Color',
    'border-Left-Style',
    'border-Left-Width',
    'border-Radius',
    'border-Right',
    'border-Right-Color',
    'border-Right-Style',
    'border-Right-Width',
    'border-Spacing',
    'border-Style',
    'border-Top',
    'border-Top-Color',
    'border-Top-Left-Radius',
    'border-Top-Right-Radius',
    'border-Top-Style',
    'border-Top-Width',
    'border-Width',
    'bottom',
    'box-Shadow',
    'box-Sizing',
    'break-After',
    'break-Before',
    'break-Inside',
    'caption-Side',
    'caret-Color',
    'clear',
    'clip',
    'clip-Path',
    'clip-Rule',
    'color',
    'color-Interpolation',
    'color-Interpolation-Filters',
    'column-Count',
    'column-Fill',
    'column-Gap',
    'column-Rule',
    'column-Rule-Color',
    'column-Rule-Style',
    'column-Rule-Width',
    'column-Span',
    'column-Width',
    'columns',
    'content',
    'counter-Increment',
    'counter-Reset',
    'css-Float',
    'css-Text',
    'cursor',
    'direction',
    'display',
    'dominant-Baseline',
    'empty-Cells',
    'fill',
    'fill-Opacity',
    'fill-Rule',
    'filter',
    'flex',
    'flex-Basis',
    'flex-Direction',
    'flex-Flow',
    'flex-Grow',
    'flex-Shrink',
    'flex-Wrap',
    'float',
    'flood-Color',
    'flood-Opacity',
    'font',
    'font-Family',
    'font-Feature-Settings',
    'font-Kerning',
    'font-Size',
    'font-Size-Adjust',
    'font-Stretch',
    'font-Style',
    'font-Synthesis',
    'font-Variant',
    'font-Variant-Caps',
    'font-Variant-East-Asian',
    'font-Variant-Ligatures',
    'font-Variant-Numeric',
    'font-Variant-Position',
    'font-Weight',
    'gap',
    'glyph-Orientation-Vertical',
    'grid',
    'grid-Area',
    'grid-Auto-Columns',
    'grid-Auto-Flow',
    'grid-Auto-Rows',
    'grid-Column',
    'grid-Column-End',
    'grid-Column-Gap',
    'grid-Column-Start',
    'grid-Gap',
    'grid-Row',
    'grid-Row-End',
    'grid-Row-Gap',
    'grid-Row-Start',
    'grid-Template',
    'grid-Template-Areas',
    'grid-Template-Columns',
    'grid-Template-Rows',
    'height',
    'hyphens',
    'image-Orientation',
    'image-Rendering',
    'inline-Size',
    'justify-Content',
    'justify-Items',
    'justify-Self',
    'left',
    'letter-Spacing',
    'lighting-Color',
    'line-Break',
    'line-Height',
    'list-Style',
    'list-Style-Image',
    'list-Style-Position',
    'list-Style-Type',
    'margin',
    'margin-Block-End',
    'margin-Block-Start',
    'margin-Bottom',
    'margin-Inline-End',
    'margin-Inline-Start',
    'margin-Left',
    'margin-Right',
    'margin-Top',
    'marker',
    'marker-End',
    'marker-Mid',
    'marker-Start',
    'mask',
    'mask-Composite',
    'mask-Image',
    'mask-Position',
    'mask-Repeat',
    'mask-Size',
    'mask-Type',
    'max-Block-Size',
    'max-Height',
    'max-Inline-Size',
    'max-Width',
    'min-Block-Size',
    'min-Height',
    'min-Inline-Size',
    'min-Width',
    'object-Fit',
    'object-Position',
    'opacity',
    'order',
    'orphans',
    'outline',
    'outline-Color',
    'outline-Offset',
    'outline-Style',
    'outline-Width',
    'overflow',
    'overflow-Anchor',
    'overflow-Wrap',
    'overflow-X',
    'overflow-Y',
    'overscroll-Behavior',
    'overscroll-Behavior-Block',
    'overscroll-Behavior-Inline',
    'overscroll-Behavior-X',
    'overscroll-Behavior-Y',
    'padding',
    'padding-Block-End',
    'padding-Block-Start',
    'padding-Bottom',
    'padding-Inline-End',
    'padding-Inline-Start',
    'padding-Left',
    'padding-Right',
    'padding-Top',
    'page-Break-After',
    'page-Break-Before',
    'page-Break-Inside',
    'paint-Order',
    'perspective',
    'perspective-Origin',
    'place-Content',
    'place-Items',
    'place-Self',
    'pointer-Events',
    'position',
    'quotes',
    'resize',
    'right',
    'rotate',
    'row-Gap',
    'ruby-Align',
    'ruby-Position',
    'scale',
    'scroll-Behavior',
    'shape-Rendering',
    'stop-Color',
    'stop-Opacity',
    'stroke',
    'stroke-Dasharray',
    'stroke-Dashoffset',
    'stroke-Linecap',
    'stroke-Linejoin',
    'stroke-Miterlimit',
    'stroke-Opacity',
    'stroke-Width',
    'tab-Size',
    'table-Layout',
    'text-Align',
    'text-Align-Last',
    'text-Anchor',
    'text-Combine-Upright',
    'text-Decoration',
    'text-Decoration-Color',
    'text-Decoration-Line',
    'text-Decoration-Style',
    'text-Emphasis',
    'text-Emphasis-Color',
    'text-Emphasis-Position',
    'text-Emphasis-Style',
    'text-Indent',
    'text-Justify',
    'text-Orientation',
    'text-Overflow',
    'text-Rendering',
    'text-Shadow',
    'text-Transform',
    'text-Underline-Position',
    'top',
    'touch-Action',
    'transform',
    'transform-Box',
    'transform-Origin',
    'transform-Style',
    'transition',
    'transition-Delay',
    'transition-Duration',
    'transition-Property',
    'transition-Timing-Function',
    'translate',
    'unicode-Bidi',
    'user-Select',
    'vertical-Align',
    'visibility',
    /** @deprecated */
    'webkit-Align-Content',
    /** @deprecated */
    'webkit-Align-Items',
    /** @deprecated */
    'webkit-Align-Self',
    /** @deprecated */
    'webkit-Animation',
    /** @deprecated */
    'webkit-Animation-Delay',
    /** @deprecated */
    'webkit-Animation-Direction',
    /** @deprecated */
    'webkit-Animation-Duration',
    /** @deprecated */
    'webkit-Animation-Fill-Mode',
    /** @deprecated */
    'webkit-Animation-Iteration-Count',
    /** @deprecated */
    'webkit-Animation-Name',
    /** @deprecated */
    'webkit-Animation-Play-State',
    /** @deprecated */
    'webkit-Animation-Timing-Function',
    /** @deprecated */
    'webkit-Appearance',
    /** @deprecated */
    'webkit-Backface-Visibility',
    /** @deprecated */
    'webkit-Background-Clip',
    /** @deprecated */
    'webkit-Background-Origin',
    /** @deprecated */
    'webkit-Background-Size',
    /** @deprecated */
    'webkit-Border-Bottom-Left-Radius',
    /** @deprecated */
    'webkit-Border-Bottom-Right-Radius',
    /** @deprecated */
    'webkit-Border-Radius',
    /** @deprecated */
    'webkit-Border-Top-Left-Radius',
    /** @deprecated */
    'webkit-Border-Top-Right-Radius',
    /** @deprecated */
    'webkit-Box-Align',
    /** @deprecated */
    'webkit-Box-Flex',
    /** @deprecated */
    'webkit-Box-Ordinal-Group',
    /** @deprecated */
    'webkit-Box-Orient',
    /** @deprecated */
    'webkit-Box-Pack',
    /** @deprecated */
    'webkit-Box-Shadow',
    /** @deprecated */
    'webkit-Box-Sizing',
    /** @deprecated */
    'webkit-Filter',
    /** @deprecated */
    'webkit-Flex',
    /** @deprecated */
    'webkit-Flex-Basis',
    /** @deprecated */
    'webkit-Flex-Direction',
    /** @deprecated */
    'webkit-Flex-Flow',
    /** @deprecated */
    'webkit-Flex-Grow',
    /** @deprecated */
    'webkit-Flex-Shrink',
    /** @deprecated */
    'webkit-Flex-Wrap',
    /** @deprecated */
    'webkit-Justify-Content',
    'webkit-Line-Clamp',
    /** @deprecated */
    'webkit-Mask',
    /** @deprecated */
    'webkit-Mask-Box-Image',
    /** @deprecated */
    'webkit-Mask-Box-Image-Outset',
    /** @deprecated */
    'webkit-Mask-Box-Image-Repeat',
    /** @deprecated */
    'webkit-Mask-Box-Image-Slice',
    /** @deprecated */
    'webkit-Mask-Box-Image-Source',
    /** @deprecated */
    'webkit-Mask-Box-Image-Width',
    /** @deprecated */
    'webkit-Mask-Clip',
    /** @deprecated */
    'webkit-Mask-Composite',
    /** @deprecated */
    'webkit-Mask-Image',
    /** @deprecated */
    'webkit-Mask-Origin',
    /** @deprecated */
    'webkit-Mask-Position',
    /** @deprecated */
    'webkit-Mask-Repeat',
    /** @deprecated */
    'webkit-Mask-Size',
    /** @deprecated */
    'webkit-Order',
    /** @deprecated */
    'webkit-Perspective',
    /** @deprecated */
    'webkit-Perspective-Origin',
    'webkit-Tap-Highlight-Color',
    /** @deprecated */
    'webkit-Text-Fill-Color',
    /** @deprecated */
    'webkit-Text-Size-Adjust',
    /** @deprecated */
    'webkit-Text-Stroke',
    /** @deprecated */
    'webkit-Text-Stroke-Color',
    /** @deprecated */
    'webkit-Text-Stroke-Width',
    /** @deprecated */
    'webkit-Transform',
    /** @deprecated */
    'webkit-Transform-Origin',
    /** @deprecated */
    'webkit-Transform-Style',
    /** @deprecated */
    'webkit-Transition',
    /** @deprecated */
    'webkit-Transition-Delay',
    /** @deprecated */
    'webkit-Transition-Duration',
    /** @deprecated */
    'webkit-Transition-Property',
    /** @deprecated */
    'webkit-Transition-Timing-Function',
    /** @deprecated */
    'webkit-User-Select',
    'white-Space',
    'widows',
    'width',
    'will-Change',
    'word-Break',
    'word-Spacing',
    'word-Wrap',
    'writing-Mode',
    'z-Index',
    /** @deprecated */
    'zoom',
]